p4i integration Integrate 209009 from 4.1 to main: Some work at doing an open source package so that it can be an the book CD. Pretty good, but I haven't tested the outputs
[git-p4: depot-paths = "//depot/qt/main/": change = 209010]

diff --git a/util/scripts/mac-binary/package/mkpackage b/util/scripts/mac-binary/package/mkpackage
--- a/util/scripts/mac-binary/package/mkpackage
+++ b/util/scripts/mac-binary/package/mkpackage
@@ -103,7 +103,7 @@ while [ -n "$1" ]; do
 	   echo "  -version <version>             What version the package is creating for (falls back to qglobal.h)"
 	   echo "  -license <license>             Where your license file lives"
 	   echo "  -license_us <license>          Where your U.S. license file lives"
-	   echo "  -licensetype <commercial|eval> The license for the package you are building"
+	   echo "  -licensetype <commercial|eval|opensource> The license for the package you are building"
 	   echo "  -readme <readme>               Where your readme file lives"
 	   echo "  -image                         Create a disk image of the outputs"
 	   echo "  -meta                          Create a meta package for all the outputs"
@@ -164,6 +164,16 @@ elif [ ! -z "$SOURCE_PACKAGE" ]; then
     rm -rf "$TMP_DIR/source"
     mkdir -p "$TMP_DIR/source"
     PACKAGE_NAME=`basename "$SOURCE_PACKAGE"`
+    CHECKLICENSETYPE=$LICENSETYPE
+    if [ "$LICENSETYPE" = "eval" ]; then
+        CHECKLICENSETYPE="commercial"
+    fi
+
+    if [ -z `echo $PACKAGE_NAME | grep $CHECKLICENSETYPE` ]; then
+        echo "I must have the $CHECKLICENSETYPE package, you gave me $SOURCE_PACKAGE"
+        rm -rf "$TMP_DIR"
+        exit 1
+    fi
     EXTENSION=`echo "$PACKAGE_NAME" | sed -e 's,.*\.tar\.\(.*\),\1,'`
     PACKAGE_DEST=`echo "$PACKAGE_NAME" | sed -e 's,\(.*\)\.tar.*,\1,'`
     if [ "$LICENSETYPE" = "eval" ]; then
@@ -200,6 +210,9 @@ if [ -z "$LICENSE" ]; then
     if [ "$LICENSETYPE" = "eval" ]; then
         DEPOT_LICENSE="$SOURCE_DIR/dist/eval/LICENSE-EVALUATION"
         PACKAGE_LICENSE="$PACKAGE_LICENSE-EVALUATION"
+    elif [ "$LICENSETYPE" = "opensource" ]; then
+        DEPOT_LICENSE="$SOURCE_DIR/dist/opensource/LICENSE.GPL"
+        PACKAGE_LICENSE="$SOURCE_DIR/LICENSE.GPL"
     fi
     if [ -e "$DEPOT_LICENSE" ]; then
         LICENSE=$DEPOT_LICENSE
@@ -210,19 +223,21 @@ if [ -z "$LICENSE" ]; then
     fi
 fi
 
-if [ -z "$LICENSE_US" ]; then
-    DEPOT_LICENSE_US="$SOURCE_DIR/dist/commercial/LICENSE-US" 
-    PACKAGE_LICENSE_US="$SOURCE_DIR/.LICENSE-US" 
-    if [ "$LICENSETYPE" = "eval" ]; then
-        DEPOT_LICENSE_US="$SOURCE_DIR/dist/eval/LICENSE-EVALUATION-US"
-        PACKAGE_LICENSE_US="$SOURCE_DIR/.LICENSE-EVALUATION-US"
-    fi
-    if [ -e "$DEPOT_LICENSE_US" ]; then
-        LICENSE_US=$DEPOT_LICENSE_US
-    elif [ -e "$PACKAGE_LICENSE_US" ]; then
-        LICENSE_US="$PACKAGE_LICENSE_US"
-    elif [ -e "../../../../dist/commercial/LICENSE-US" ]; then
-	LICENSE_US="../../../../dist/commercial/LICENSE-US"
+if [ "$LICENSETYPE" != "opensource" ]; then
+    if [ -z "$LICENSE_US" ]; then
+        DEPOT_LICENSE_US="$SOURCE_DIR/dist/commercial/LICENSE-US" 
+        PACKAGE_LICENSE_US="$SOURCE_DIR/.LICENSE-US" 
+        if [ "$LICENSETYPE" = "eval" ]; then
+            DEPOT_LICENSE_US="$SOURCE_DIR/dist/eval/LICENSE-EVALUATION-US"
+            PACKAGE_LICENSE_US="$SOURCE_DIR/.LICENSE-EVALUATION-US"
+        fi
+        if [ -e "$DEPOT_LICENSE_US" ]; then
+            LICENSE_US=$DEPOT_LICENSE_US
+        elif [ -e "$PACKAGE_LICENSE_US" ]; then
+            LICENSE_US="$PACKAGE_LICENSE_US"
+        elif [ -e "../../../../dist/commercial/LICENSE-US" ]; then
+            LICENSE_US="../../../../dist/commercial/LICENSE-US"
+        fi
     fi
 fi
 
@@ -260,14 +275,16 @@ if [ "$QT_SET_VERSION" = "no" ] && [ ! -z "$SOURCE_DIR" ]; then
     fi
 fi
 
-if [ ! -z "$SOURCE_DIR" ]; then
-    PACKAGEDATE=`grep '^# *define *QT_PACKAGEDATE_STR' $SOURCE_DIR/src/corelib/global/qglobal.h`
-    if [ -n "$PACKAGEDATE" ]; then
-        PACKAGEDATE=`echo $PACKAGEDATE | sed 's,^# *define *QT_PACKAGEDATE_STR "*\([^ ]*\)"$,\1,'`
-        QT_PACKAGEDATE_STRING=$PACKAGEDATE
-    else
-        echo "Cannot process date information from qglobal.h: $PACKAGEDATE"
-    fi
+if [ "$LICENSETYPE" != "opensource" ]; then
+	if [ ! -z "$SOURCE_DIR" ]; then
+	    PACKAGEDATE=`grep '^# *define *QT_PACKAGEDATE_STR' $SOURCE_DIR/src/corelib/global/qglobal.h`
+	    if [ -n "$PACKAGEDATE" ]; then
+		PACKAGEDATE=`echo $PACKAGEDATE | sed 's,^# *define *QT_PACKAGEDATE_STR "*\([^ ]*\)"$,\1,'`
+		QT_PACKAGEDATE_STRING=$PACKAGEDATE
+	    else
+		echo "Cannot process date information from qglobal.h: $PACKAGEDATE"
+	    fi
+	fi
 fi
 
 # Put the date in a little file so we can access in later
@@ -311,28 +328,30 @@ else
    exit 1
 fi
 
-if [ -e "$LICENSE_US" ]; then
-   echo "Creating license richtext for U.S."
-   createLicenseRTF "$LICENSE_US" "$TMP_DIR/licenses/License-US.rtf"
-else
-   echo "No U.S. license file found!"
-   exit 1
+if [ "$LICENSETYPE" != "opensource" ]; then
+    if [ -e "$LICENSE_US" ]; then
+       echo "Creating license richtext for U.S."
+       createLicenseRTF "$LICENSE_US" "$TMP_DIR/licenses/License-US.rtf"
+    else
+       echo "No U.S. license file found!"
+       exit 1
+    fi
+
+    # build the InstallerPane plugin
+    INSTALLERPANE_PATH=InstallerPane
+    INSTALLERPANE_CONFIGURATION="Release-$LICENSETYPE"
+    INSTALLERPANE_BUILDPARAMS="-project ""$INSTALLERPANE_PATH/InstallerPane.xcodeproj"" -configuration ""$INSTALLERPANE_CONFIGURATION"
+
+    echo "/usr/bin/xcodebuild $INSTALLERPANE_BUILDPARAMS"
+    if !(/usr/bin/xcodebuild $INSTALLERPANE_BUILDPARAMS || grep '** BUILD SUCCEEDED **'); then
+        echo "Could not build installer pane plugin"
+        exit 100;
+    fi
+
+    # Create the key decoder for the script version
+    BUILD_LINE="keydecoder/main.cpp $INSTALLERPANE_PATH/keydec.cpp -o Resources/keydecoder -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk"
+    /usr/bin/g++-4.0 $BUILD_LINE
 fi
-
-# build the InstallerPane plugin
-INSTALLERPANE_PATH=InstallerPane
-INSTALLERPANE_CONFIGURATION="Release-$LICENSETYPE"
-INSTALLERPANE_BUILDPARAMS="-project ""$INSTALLERPANE_PATH/InstallerPane.xcodeproj"" -configuration ""$INSTALLERPANE_CONFIGURATION"
-
-echo "/usr/bin/xcodebuild $INSTALLERPANE_BUILDPARAMS"
-if !(/usr/bin/xcodebuild $INSTALLERPANE_BUILDPARAMS || grep '** BUILD SUCCEEDED **'); then
-    echo "Could not build installer pane plugin"
-    exit 100;
-fi
-
-# Create the key decoder for the script version
-BUILD_LINE="keydecoder/main.cpp $INSTALLERPANE_PATH/keydec.cpp -o Resources/keydecoder -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk"
-/usr/bin/g++-4.0 $BUILD_LINE
 
 #create the packages
 PKG_CREATED=
@@ -389,15 +408,20 @@ for package in $PACKAGES; do
     cp -R "$PACKAGEDATE_FILE" "$package_dir/Contents/Resources"
     cp -R $PACKAGE_DIR/$package/Resources/* "$package_dir/Contents/Resources"
     cp "Welcome-$LICENSETYPE.rtf" "$package_dir/Contents/Resources/Welcome.rtf"
-    for lang in "North and South America" "Rest of the world"; do
-        LOCALDIR="$package_dir/Contents/Resources/${lang}.lproj"
-        mkdir -p "$LOCALDIR"
-        if [ "$lang" == "North and South America" ]; then
-            cp "$TMP_DIR/licenses/License-US.rtf" "$LOCALDIR/License.rtf"
-        else
-            cp "$TMP_DIR/licenses/License.rtf" "$LOCALDIR"
-        fi
-    done
+    cp "$README" "$package_dir/Contents/Resources/ReadMe.txt"
+    if [ $LICENSETYPE != "opensource" ]; then
+        for lang in "North and South America" "Rest of the world"; do
+            LOCALDIR="$package_dir/Contents/Resources/${lang}.lproj"
+            mkdir -p "$LOCALDIR"
+            if [ "$lang" == "North and South America" ]; then
+                cp "$TMP_DIR/licenses/License-US.rtf" "$LOCALDIR/License.rtf"
+            else
+                cp "$TMP_DIR/licenses/License.rtf" "$LOCALDIR"
+            fi
+        done
+    else
+        cp "$TMP_DIR/licenses/License.rtf" "$package_dir/Contents/Resources"
+    fi
     for a in $package_dir/Contents/Resources/*.plist $package_dir/Contents/Resources/*.info $package_dir/Contents/Resources/*flight $package_dir/Contents/Resources/*.rtf; do
 	[ -e "$a" ] && doStringReplace "$a" "$a"
     done
@@ -420,13 +444,17 @@ for package in $PACKAGES; do
             fi
         fi
     done
-    # Copy over the plugin
-    plugin_dir="$package_dir/Contents/Plugins"
-    mkdir "$plugin_dir"
-    cp -r "$INSTALLERPANE_PATH/build/$INSTALLERPANE_CONFIGURATION/InstallerPane.bundle" "$plugin_dir"
-    cp "$INSTALLERPANE_PATH/InstallerSections.plist" "$plugin_dir"
+    if [ "$LICENSETYPE" != "opensource" ]; then
+        # Copy over the plugin
+        plugin_dir="$package_dir/Contents/Plugins"
+        mkdir "$plugin_dir"
+        cp -r "$INSTALLERPANE_PATH/build/$INSTALLERPANE_CONFIGURATION/InstallerPane.bundle" "$plugin_dir"
+        cp "$INSTALLERPANE_PATH/InstallerSections.plist" "$plugin_dir"
 
-    if [ "$package" != "debuglibraries" ]; then
+        if [ "$package" != "debuglibraries" ]; then
+            PKG_CREATED="$PKG_CREATED $package_dir"
+        fi
+    else
         PKG_CREATED="$PKG_CREATED $package_dir"
     fi
 done
@@ -444,25 +472,32 @@ if [ "$MAKE_META" = "yes" ]; then
     mkdir -p "$OUTPUT_DIR/Qt.mpkg/"
     cp -R "MetaPackage" "$OUTPUT_DIR/Qt.mpkg/Contents"
 
-    # Copy over the plugin
-    plugin_dir="$OUTPUT_DIR/Qt.mpkg/Contents/Plugins"
-    mkdir -p "$plugin_dir"
-    cp -r "$INSTALLERPANE_PATH/build/$INSTALLERPANE_CONFIGURATION/InstallerPane.bundle" "$plugin_dir"
-    cp "$INSTALLERPANE_PATH/InstallerSections.plist" "$plugin_dir"
+    if [ $LICENSETYPE != "opensource" ]; then
+        # Copy over the plugin
+        plugin_dir="$OUTPUT_DIR/Qt.mpkg/Contents/Plugins"
+        mkdir -p "$plugin_dir"
+        cp -r "$INSTALLERPANE_PATH/build/$INSTALLERPANE_CONFIGURATION/InstallerPane.bundle" "$plugin_dir"
+        cp "$INSTALLERPANE_PATH/InstallerSections.plist" "$plugin_dir"
+    fi
 
     mkdir -p "$OUTPUT_DIR/Qt.mpkg/Contents/Resources"
     cp -R Resources/* "$OUTPUT_DIR/Qt.mpkg/Contents/Resources"
     cp -R "$PACKAGEDATE_FILE" "$OUTPUT_DIR/Qt.mpkg/Contents/Resources"
     cp "Welcome-${LICENSETYPE}.rtf" "$OUTPUT_DIR/Qt.mpkg/Contents/Resources/Welcome.rtf"
-    for lang in "North and South America" "Rest of the world"; do
-        LOCALDIR="$OUTPUT_DIR/Qt.mpkg/Contents/Resources/${lang}.lproj"
-        mkdir -p "$LOCALDIR"
-        if [ "$lang" == "North and South America" ]; then
-            cp "$TMP_DIR/licenses/License-US.rtf" "$LOCALDIR/License.rtf"
-        else
-            cp "$TMP_DIR/licenses/License.rtf" "$LOCALDIR"
-        fi
-    done
+    cp "$README" "$OUTPUT_DIR/Qt.mpkg/Contents/Resources/ReadMe.txt"
+    if [ $LICENSETYPE != "opensource" ]; then
+        for lang in "North and South America" "Rest of the world"; do
+            LOCALDIR="$OUTPUT_DIR/Qt.mpkg/Contents/Resources/${lang}.lproj"
+            mkdir -p "$LOCALDIR"
+            if [ "$lang" == "North and South America" ]; then
+                cp "$TMP_DIR/licenses/License-US.rtf" "$LOCALDIR/License.rtf"
+            else
+                cp "$TMP_DIR/licenses/License.rtf" "$LOCALDIR"
+            fi
+        done
+    else
+        cp "$TMP_DIR/licenses/License.rtf" "$OUTPUT_DIR/Qt.mpkg/Contents/Resources"
+    fi
     for a in $OUTPUT_DIR/Qt.mpkg/Contents/*.plist $OUTPUT_DIR/Qt.mpkg/Contents/Resources/*.info $OUTPUT_DIR/Qt.mpkg/Contents/Resources/*.plist $OUTPUT_DIR/Qt.mpkg/Contents/Resources/*.rtf; do
 	doStringReplace "$a" "$a"
     done
