p4i integration Integrate 234916 from 4.2 to main: Fixes: adds metered licensing to Qt Task:  114195 RevBy: none AutoTest: none Details:
moc, qmake, uic and designer now all tries to report Qt usage if qtusagereporter can be found
in the BinariesPath

configure and configure.exe now supports meterede licences, and deletes any qtusagereporter
it finds in bin/ unless it's a metered license

mkdist.qs removes any bin/qtusagereporter it finds for opensource packages

[git-p4: depot-paths = "//depot/qt/main/": change = 234917]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -344,7 +344,7 @@ EOF
         esac
     fi
     case "$LicenseFeatureCode" in
-    G)
+    G|L)
         # US
         case "$LicenseType" in
         Commercial)
@@ -361,7 +361,7 @@ EOF
             ;;
         esac
         ;;
-    2)
+    2|5)
         # non-US
         case "$LicenseType" in
         Commercial)
@@ -377,6 +377,24 @@ EOF
             cp -f "$relpath/.LICENSE-EDUCATIONAL" "$outpath/LICENSE"
             ;;
         esac
+        ;;
+    *)
+        echo
+        echo "Invalid license key. Please check the license key."
+        exit 1
+        ;;
+    esac
+    case "$LicenseFeatureCode" in
+    G|2)
+        # delete qtusagereporter for non-metered licenses
+        rm -f "$relpath/bin/qtusagereporter"
+        ;;
+    L|5)
+        # copy qtusagereporter for metered licenses
+        if [ '!' -f "$outpath/bin/qtusagereporter" ]; then
+            mkdir -p "$outpath/bin"
+            cp -f "$relpath/bin/qtusagereporter" "$outpath/bin/qtusagereporter"
+        fi
         ;;
     *)
         echo
