p4i integration Integrate change 79385 from 3.1 to main. Description for change 79385:
: Change 79385 by sam@sam-stumpy on 2002/11/11 01:22:15
: 
: 	seems like a bit of a risk to just run make/gmake blindly - can't
: 	we just use which (we do in other places in thes script...)
: 
: Affected files ...
: 
: ... //depot/qt/3.1/configure#4 edit

[git-p4: depot-paths = "//depot/qt/main/": change = 79386]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1094,16 +1094,20 @@ if [ "$OPT_FAST" = "auto" ]; then
 fi
 
 # find a make command
-if ( gmake /dev/null ) >/dev/null 2>&1; then
-    MAKE=gmake
-else
-    if ( make /dev/null ) >/dev/null 2>&1; then
-	MAKE=make
-    else
-	echo "You don't seem to have 'make' or 'gmake' in your PATH."
-	echo "Cannot proceed."
-	exit 1
+MAKE=
+for mk in gmake make; do
+    if which $mk >/dev/null 2>&1; then
+	where_mk=`which $mk`
+	if [ -x "$where_mk" ]; then
+	    MAKE="$mk"
+	    break
+	fi
     fi
+done
+if [ -z "$MAKE" ]; then
+    echo "You don't seem to have 'make' or 'gmake' in your PATH."
+    echo "Cannot proceed."
+    exit 1
 fi
 
 fi ### help
