Fixes:    Adds autodetection support for database drivers Task: AutoTest: none Details:
[git-p4: depot-paths = "//depot/qt/main/": change = 194708]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -376,8 +376,6 @@ CFG_OPENGL=auto
 CFG_FONTCONFIG=auto
 CFG_QWS_FREETYPE=yes
 CFG_SQL_AVAILABLE=
-CFG_SQL_ON=
-CFG_SQL_AUTODETECTED=
 CFG_GFX_AVAILABLE="repeater"
 CFG_GFX_ON=""
 CFG_GFX_OFF=""
@@ -449,6 +447,11 @@ QT_INSTALL_DEMOS=
 
 CFG_SQL_AVAILABLE=`find $relpath/src/plugins/sqldrivers/* -prune -type d -exec basename {} \;`
 CFG_SQL_AVAILABLE=`echo $CFG_SQL_AVAILABLE`               # normalize whitespace
+# by default, auto-detect which sql drivers can be built
+for i in $CFG_SQL_AVAILABLE; do
+    eval "CFG_SQL_$i=auto"
+done
+
 CFG_DECORATION_AVAILABLE=""
 if [ -d "$relpath/src/plugins/decorations" ]; then
     CFG_DECORATION_AVAILABLE=`find $relpath/src/plugins/decorations/* -prune -type d -exec basename {} \;`
@@ -1070,21 +1073,25 @@ while [ "$#" -gt 0 ]; do
         VAR=`echo $VAR | sed "s,^\([^-]*\).*,\1,"`
         ERROR=no
         if [ "$VAR" = "decoration" ]; then
-            ERROR=yes
+            ERROR=yes            
             for d in $CFG_DECORATION_AVAILABLE; do
                 if [ "$VAL" = "$d" ]; then
                     ERROR=no
                     break
                 fi
-            done
+            done            
         elif [ "$VAR" = "sql" ]; then
             ERROR=yes
+            # check if named driver is available
             for d in $CFG_SQL_AVAILABLE; do
                 if [ "$VAL" = "$d" ]; then
                     ERROR=no
                     break
                 fi
             done
+            # set the CFG_SQL_driver
+            eval "CFG_SQL_$VAL=\$OPT"
+            continue
         fi
         if [ "$OPT" = "plugin" ] || [ "$OPT" = "qt" ]; then
             if [ "$OPT" = "plugin" ]; then
@@ -1092,8 +1099,7 @@ while [ "$#" -gt 0 ]; do
                 [ "$VAR" = "decoration" ] && CFG_DECORATION_ON=`echo "${CFG_DECORATION_ON} " | sed "s,${VAL} ,,g"` && CFG_DECORATION_PLUGIN="$CFG_DECORATION_PLUGIN ${VAL}"
                 VAR="${VAR}-${OPT}"
             else
-                if [ "$VAR" = "sql" ] || [ "$VAR" = "gfx" ] || [ "$VAR" = "kbd" ] || [ "$VAR" = "mouse" ]; then
-                    [ "$VAR" = "sql" ] && CFG_SQL_ON="$CFG_SQL_ON $VAL"
+                if [ "$VAR" = "gfx" ] || [ "$VAR" = "kbd" ] || [ "$VAR" = "mouse" ]; then
                     [ "$VAR" = "gfx" ] && CFG_GFX_ON="$CFG_GFX_ON $VAL"
                     [ "$VAR" = "kbd" ] && CFG_KBD_ON="$CFG_KBD_ON $VAL"
                     [ "$VAR" = "mouse" ] && CFG_MOUSE_ON="$CFG_MOUSE_ON $VAL"
@@ -1103,13 +1109,12 @@ while [ "$#" -gt 0 ]; do
             QMAKE_VARS="$QMAKE_VARS \"${VAR}s += $VAL\""
         elif [ "$OPT" = "no" ]; then
             PLUG_VAR="${VAR}-plugin"
-            if [ "$VAR" = "sql" ] || [ "$VAR" = "gfx" ] || [ "$VAR" = "kbd" ] || [ "$VAR" = "mouse" ]; then
+            if [ "$VAR" = "gfx" ] || [ "$VAR" = "kbd" ] || [ "$VAR" = "mouse" ]; then
                 IN_VAR="${VAR}-driver"
             else
                 IN_VAR="${VAR}"
             fi
             [ "$VAR" = "decoration" ] && CFG_DECORATION_ON=`echo "${CFG_DECORATION_ON} " | sed "s,${VAL} ,,g"`
-            [ "$VAR" = "sql" ] && CFG_SQL_ON=`echo "${CFG_SQL_ON} " | sed "s,${VAL} ,,g"`
             [ "$VAR" = "gfx" ] && CFG_GFX_ON=`echo "${CFG_GFX_ON} " | sed "s,${VAL} ,,g"`
             [ "$VAR" = "kbd" ] && CFG_KBD_ON=`echo "${CFG_KBD_ON} " | sed "s,${VAL} ,,g"`
             [ "$VAR" = "mouse" ] && CFG_MOUSE_ON=`echo "${CFG_MOUSE_ON} " | sed "s,${VAL} ,,g"`
@@ -1996,9 +2001,6 @@ fi
                          Possible values for <driver>:
                          [ $CFG_SQL_AVAILABLE ]
 
-                         Auto-Detected on this system:
-                         [$CFG_SQL_AUTODETECTED ]
-
                          By default none of the SQL drivers are built,
                          even if they are auto-detected.
 
@@ -2722,37 +2724,179 @@ if [ "$CFG_ACCESSIBILITY" = "auto" ]; then
 fi
 
 # auto-detect SQL-modules support
-MYSQL_REQ="-lmysqlclient mysql.h"
 for _SQLDR in $CFG_SQL_AVAILABLE; do
         case $_SQLDR in
         mysql)
-            $unixtests/checkavail "MySQL" $OPT_VERBOSE $MYSQL_REQ $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED mysql"
+	    if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/mysql_r "MySQL (thread-safe)" $L_FLAGS $I_FLAGS; then
+                QMAKE_VARS="$QMAKE_VARS \"CONFIG += use_libmysqlclient_r\""
+                if [ "$CFG_SQL_mysql" = "auto" ]; then
+                    CFG_SQL_mysql=plugin
+                fi
+            elif $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/mysql "MySQL (thread-unsafe)" $L_FLAGS $I_FLAGS; then
+                if [ "$CFG_SQL_mysql" = "auto" ]; then
+                    CFG_SQL_mysql=plugin
+                fi
+            else
+                if [ "$CFG_SQL_psql" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                    echo "MySQL support cannot be enabled due to functionality tests!"
+                    echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                    echo " If you believe this message is in error you may use the continue"
+                    echo " switch (-continue) to $0 to continue."
+                    exit 101
+                else
+                    CFG_SQL_mysql=no
+                fi
+            fi            	
         ;;
-        psql)
-            $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/psql "PostgreSQL" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED psql"
-            ;;
+        psql)                        
+            if [ "$CFG_SQL_psql" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/psql "PostgreSQL" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_psql" = "auto" ]; then
+                        CFG_SQL_psql=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_psql" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "PostgreSQL support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_psql=no
+                    fi
+                fi 
+            fi                        
+        ;;
         odbc)
-	    $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/odbc "ODBC" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED odbc"
+            if [ "$CFG_SQL_odbc" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/odbc "ODBC" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_odbc" = "auto" ]; then
+                        CFG_SQL_odbc=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_odbc" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "ODBC support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_odbc=no
+                    fi
+                fi 
+            fi            
             ;;
         oci)
-            $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/oci "OCI" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED oci"
+            if [ "$CFG_SQL_oci" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/oci "OCI" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_oci" = "auto" ]; then
+                        CFG_SQL_oci=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_oci" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "Oracle (OCI) support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_oci=no
+                    fi
+                fi 
+            fi            
             ;;
         tds)
-            $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/tds "TDS" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED tds"
+            if [ "$CFG_SQL_tds" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/tds "TDS" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_tds" = "auto" ]; then
+                        CFG_SQL_tds=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_tds" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "TDS support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_tds=no
+                    fi
+                fi 
+            fi            
             ;;
         db2)
-            $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/db2 "DB2" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED db2"
+            if [ "$CFG_SQL_db2" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/db2 "DB2" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_db2" = "auto" ]; then
+                        CFG_SQL_db2=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_db2" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "ODBC support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_db2=no
+                    fi
+                fi 
+            fi            
             ;;
         ibase)
-            $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/ibase "InterBase" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED ibase"
+            if [ "$CFG_SQL_ibase" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/ibase "InterBase" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_ibase" = "auto" ]; then
+                        CFG_SQL_ibase=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_ibase" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "InterBase support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_ibase=no
+                    fi
+                fi 
+            fi            
             ;;
         sqlite2)
-            $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/sqlite2 "SQLite2" $L_FLAGS $I_FLAGS && CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED sqlite2"
+            if [ "$CFG_SQL_sqlite2" != "no" ]; then
+                if $unixtests/compile.test $XQMAKESPEC $OPT_VERBOSE $relpath $outpath config.tests/unix/sqlite2 "SQLite2" $L_FLAGS $I_FLAGS; then
+                    if [ "$CFG_SQL_sqlite2" = "auto" ]; then
+                        CFG_SQL_sqlite2=plugin
+                    fi
+                else
+                    if [ "$CFG_SQL_sqlite2" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                        echo "SQLite2 support cannot be enabled due to functionality tests!"
+                        echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                        echo " If you believe this message is in error you may use the continue"
+                        echo " switch (-continue) to $0 to continue."
+                        exit 101
+                    else
+                        CFG_SQL_sqlite2=no
+                    fi
+                fi 
+            fi            
             ;;
         sqlite)
             if [ -f $relpath/src/3rdparty/sqlite/sqlite3.h ]; then
-                CFG_SQL_AUTODETECTED="$CFG_SQL_AUTODETECTED sqlite"
-            fi
+                if [ "$CFG_SQL_sqlite" = "auto" ]; then
+                        CFG_SQL_sqlite=plugin
+                fi    
+            else
+                if [ "$CFG_SQL_sqlite" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+                    echo "SQLite support cannot be enabled due to functionality tests!"
+                    echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                    echo " If you believe this message is in error you may use the continue"
+                    echo " switch (-continue) to $0 to continue."
+                    exit 101
+                else
+                    CFG_SQL_sqlite=no
+                fi
+            fi                        
             ;;
         *)
             if [ "$OPT_VERBOSE" = "yes" ]; then
@@ -3644,10 +3788,22 @@ if [ "$PLATFORM_QWS" = "yes" ]; then
 fi # QWS
 
 # Add turned on SQL drivers
-for DRIVER in $CFG_SQL_ON; do
-    ONDRIVER=`echo $DRIVER | tr '[:lower:]' '[:upper:]'`
-    QCONFIG_FLAGS="$QCONFIG_FLAGS QT_SQL_$ONDRIVER"
+for DRIVER in $CFG_SQL_AVAILABLE; do
+    eval "VAL=\$CFG_SQL_$DRIVER"
+    case "$VAL" in
+    qt)
+        ONDRIVER=`echo $DRIVER | tr '[:lower:]' '[:upper:]'`
+        QCONFIG_FLAGS="$QCONFIG_FLAGS QT_SQL_$ONDRIVER"
+        SQL_DRIVERS="$SQL_DRIVERS $DRIVER"
+    ;;
+    plugin)    
+        SQL_PLUGINS="$SQL_PLUGINS $DRIVER"
+    ;; 
+    esac               
 done
+
+QMAKE_VARS="$QMAKE_VARS \"sql-drivers = $SQL_DRIVERS\"" 
+QMAKE_VARS="$QMAKE_VARS \"sql-plugins = $SQL_PLUGINS\"" 
 
 # Add other configuration options to the qconfig.h file
 [ "$CFG_GIF" = "yes" ]       && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_BUILTIN_GIF_READER=1"
