Fixes:    Add configure-time check for libdbus-1 >= 0.62 Details:  I'll integrate the QtDBus module soon and this is the test that is required for it.
[git-p4: depot-paths = "//depot/qt/main/": change = 224245]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -427,6 +427,9 @@ fi
 # QTDIR may be set and point to an old or system-wide Qt installation
 unset QTDIR
 
+# the minimum version of libdbus-1 that we require:
+MIN_DBUS_1_VERSION=0.62
+
 # initalize internal variables
 CFG_CONFIGURE_EXIT_ON_ERROR=yes
 CFG_PROFILE=no
@@ -491,6 +494,7 @@ CFG_XKB=auto
 CFG_NIS=auto
 CFG_CUPS=auto
 CFG_ICONV=auto
+CFG_QTDBUS=auto
 CFG_GLIB=auto
 CFG_LARGEFILE=auto
 CFG_STL=auto
@@ -549,6 +553,10 @@ QT_LFLAGS_MYSQL=
 QT_LFLAGS_MYSQL_R=
 QT_CFLAGS_SQLITE=
 QT_LFLAGS_SQLITE=
+
+# flags for libdbus-1
+QT_CFLAGS_DBUS=
+QT_LIBS_DBUS=
 
 # flags for Glib (X11 only)
 QT_CFLAGS_GLIB=
@@ -626,7 +634,7 @@ while [ "$#" -gt 0 ]; do
         VAL=no
         ;;
     #Qt style yes options
-        -incremental|-qvfb|-profile|-shared|-static|-sm|-xinerama|-xshape|-tablet|-reduce-exports|-pch|-stl|-freetype|-xcursor|-xfixes|-xrandr|-xrender|-fontconfig|-xkb|-nis|-glib|-cups|-iconv|-largefile|-h|-help|-v|-verbose|-debug|-release|-fast|-opengl|-accessibility|-confirm-license|-gnumake|-framework|-qt3support|-debug-and-release|-exceptions|-universal|-prefix-install|-silent)
+        -incremental|-qvfb|-profile|-shared|-static|-sm|-xinerama|-xshape|-tablet|-reduce-exports|-pch|-stl|-freetype|-xcursor|-xfixes|-xrandr|-xrender|-fontconfig|-xkb|-nis|-qtdbus|-glib|-cups|-iconv|-largefile|-h|-help|-v|-verbose|-debug|-release|-fast|-opengl|-accessibility|-confirm-license|-gnumake|-framework|-qt3support|-debug-and-release|-exceptions|-universal|-prefix-install|-silent)
         VAR=`echo $1 | sed "s,^-\(.*\),\1,"`
         VAL=yes
         ;;
@@ -1212,6 +1220,13 @@ while [ "$#" -gt 0 ]; do
     glib)
         if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
             CFG_GLIB="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    qtdbus)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            CFG_QTDBUS="$VAL"
         else
             UNKNOWN_OPT=yes
         fi
@@ -2387,6 +2402,13 @@ else
     EXCN=" "
     EXCY="*"
 fi
+if [ "$CFG_QTDBUS" = "no" ]; then
+    DBY=" "
+    DBN="+"
+else
+    DBY="+"
+    DBN=" "
+fi
     cat << EOF
  $EXCN  -no-exceptions ..... Disable exceptions on compilers that support it.
  $EXCY  -exceptions ........ Enable exceptions on compilers that support it.
@@ -2483,6 +2505,9 @@ Additional options:
 
  $PHN  -no-pch ............ Do not use precompiled header support.
  $PHY  -pch ............... Use precompiled header support.
+
+ $DBN  -no-qtdbus.......... Do not compile the QtDBus module.
+ $DBY  -qtdbus............. Compile the QtDBus module.
 
 EOF
 
@@ -3497,6 +3522,28 @@ if [ "$CFG_ICONV" != "no" ]; then
     fi
 fi
 
+# auto-detect libdbus-1 support
+if [ "$CFG_QTDBUS" != "no" ]; then
+    if "$WHICH" pkg-config >/dev/null 2>&1 && \
+	pkg-config --atleast-version="$MIN_DBUS_1_VERSION" dbus-1 2>/dev/null; then
+        QT_CFLAGS_GLIB=`pkg-config --cflags dbus-1`
+        QT_LIBS_GLIB=`pkg-config --libs dbus-1`
+        CFG_QTDBUS=yes
+	QMakeVar set QT_CFLAGS_GLIB "$QT_CFLAGS_GLIB"
+	QMakeVar set QT_LIBS_GLIB "$QT_LIBS_GLIB"
+    else
+        if [ "$CFG_QTDBUS" = "yes" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+            echo "The QtDBus module cannot be enabled because libdbus-1 version $MIN_DBUS_1_VERSION was not found."
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_QTDBUS=no
+        fi
+    fi
+fi
+
 # x11
 if [ "$PLATFORM_X11" = "yes" ]; then
     x11tests="$relpath/config.tests/x11"
@@ -4035,6 +4082,7 @@ fi
 [ "$CFG_ICONV" = "yes" ] && QT_CONFIG="$QT_CONFIG iconv"
 [ "$CFG_ICONV" = "gnu" ] && QT_CONFIG="$QT_CONFIG gnu-libiconv"
 [ "$CFG_GLIB" = "yes" ] && QT_CONFIG="$QT_CONFIG glib"
+[ "$CFG_QTDBUS" = "yes" ] && QT_CONFIG="$QT_CONFIG qtdbus"
 [ "$CFG_NAS" = "system" ] && QT_CONFIG="$QT_CONFIG nas"
 
 if [ "$PLATFORM_X11" = "yes" ]; then
@@ -4428,8 +4476,9 @@ QMakeVar set sql-plugins "$SQL_PLUGINS"
 
 # X11/Unix/Mac only configs
 [ "$CFG_CUPS" = "no" ]       && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_CUPS"
-[ "$CFG_ICONV" = "no" ]       && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_ICONV"
-[ "$CFG_GLIB" != "yes" ]       && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_GLIB"
+[ "$CFG_ICONV" = "no" ]      && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_ICONV"
+[ "$CFG_GLIB" != "yes" ]     && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_GLIB"
+[ "$CFG_QTDBUS" != "yes" ]   && QCONFIG_FLAGS="$QCONFIG-FLAGS QT_NO_QTDBUS"
 [ "$CFG_GETADDRINFO" = "no" ]&& QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_GETADDRINFO"
 [ "$CFG_IPV6IFNAME" = "no" ] && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_IPV6IFNAME"
 [ "$CFG_GETIFADDRS" = "no" ] && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_GETIFADDRS"
@@ -4729,6 +4778,7 @@ else
    echo "Debug................ $CFG_DEBUG"
 fi
 echo "Qt3 compatibility.... $CFG_QT3SUPPORT"
+echo "QtDBus module........ $CFG_QTDBUS"
 echo "STL support ......... $CFG_STL"
 echo "PCH support ......... $CFG_PRECOMPILE"
 echo "MMX/SSE support ..... $CFG_HAVE_SSE"
