decode the package date out of qglobal.h and use this to verify that the user is actually licensed to use Qt...
in particular, if the date in the commercial is after the license's
expiry date, configure refuses to continue... in the eval package, if
today's date is after the license's expiry date, configure refuses to
continue

[git-p4: depot-paths = "//depot/qt/main/": change = 195272]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -88,6 +88,13 @@ if [ -z "$QT_MAJOR_VERSION" ]; then
    exit 1
 fi
 
+QT_PACKAGEDATE=`grep '^# *define *QT_PACKAGEDATE_STR' $relpath/src/corelib/global/qglobal.h | sed -e 's,^# *define *QT_PACKAGEDATE_STR *"\([^ ]*\)"$,\1,' -e s,-,,g`
+if [ -z "$QT_PACKAGEDATE" ]; then
+   echo "Unable to determine package date from qglobal.h: '$QT_PACKAGEDATE'"
+   echo "Cannot proceed"
+   exit 1
+fi
+
 #-------------------------------------------------------------------------------
 # check the license
 #-------------------------------------------------------------------------------
@@ -2389,23 +2396,57 @@ elif [ "$Edition" != "Trolltech" ]; then
         [ -z "$ExpiryDate" ] && ExpiryDate="0"
         Today=`date +%Y%m%d`
         if [ "$Today" -gt "$ExpiryDate" ]; then
-            echo
-            echo "WARNING  WARNING  WARNING  WARNING"
-            echo
-            echo "  Your support and upgrade period has expired."
-            echo
-            echo "  You may continue to use your last licensed release"
-            echo "  of Qt under the terms of your existing license"
-            echo "  agreement. But you are not entitled to technical"
-            echo "  support, nor are you entitled to use any more recent"
-            echo "  Qt releases."
-            echo
-            echo "  Please contact sales@trolltech.com to renew your"
-            echo "  support and upgrades for this license."
-            echo
-            echo "WARNING  WARNING  WARNING  WARNING"
-            echo
-            sleep 3
+            case "$LicenseType" in
+            Commercial|Academic|Educational)
+                if [ "$QT_PACKAGEDATE" -gt "$ExpiryDate" ]; then
+                    echo
+                    echo "NOTICE  NOTICE  NOTICE  NOTICE"
+                    echo
+                    echo "  Your support and upgrade period has expired."
+                    echo
+                    echo "  You are no longer licensed to use this version of Qt."
+                    echo "  Please contact sales@trolltech.com to renew your support"
+                    echo "  and upgrades for this license."
+                    echo
+                    echo "NOTICE  NOTICE  NOTICE  NOTICE"
+                    echo
+                    exit 1
+                else
+                    echo
+                    echo "WARNING  WARNING  WARNING  WARNING"
+                    echo
+                    echo "  Your support and upgrade period has expired."
+                    echo
+                    echo "  You may continue to use your last licensed release"
+                    echo "  of Qt under the terms of your existing license"
+                    echo "  agreement. But you are not entitled to technical"
+                    echo "  support, nor are you entitled to use any more recent"
+                    echo "  Qt releases."
+                    echo
+                    echo "  Please contact sales@trolltech.com to renew your"
+                    echo "  support and upgrades for this license."
+                    echo
+                    echo "WARNING  WARNING  WARNING  WARNING"
+                    echo
+                    sleep 3
+                fi
+                ;;
+            Evaluation|*)
+                echo
+                echo "NOTICE  NOTICE  NOTICE  NOTICE"
+                echo
+                echo "  Your Evaluation license has expired."
+                echo
+                echo "  You are no longer licensed to use this software. Please"
+                echo "  contact sales@trolltech.com to purchase license, or install"
+                echo "  the Qt Open Source Edition if you intend to develop free"
+                echo "  software."
+                echo
+                echo "NOTICE  NOTICE  NOTICE  NOTICE"
+                echo
+                exit 1
+                ;;
+            esac
         fi
     fi
     TheLicense=`head -n 1 LICENSE`
