warnings to stderr
[imported from CVS by cvs2p4 at 1999/10/31 20:19:02]

[git-p4: depot-paths = "//depot/qt/main/": change = 9813]

diff --git a/util/scripts/mkconfigs b/util/scripts/mkconfigs
--- a/util/scripts/mkconfigs
+++ b/util/scripts/mkconfigs
@@ -50,7 +50,7 @@ do
 	then
 	    mk $platform static-debug
 	else
-	    echo "$platform cannot do static-debug"
+	    echo >&2 "$platform cannot do static-debug"
 	fi
 
 	# Dynamic linking?
@@ -62,10 +62,10 @@ do
 	    then
 		mk $platform shared-debug
 	    else
-		echo "$platform cannot do shared-debug"
+		echo >&2 "$platform cannot do shared-debug"
 	    fi
 	else
-	    echo "$platform cannot do shared (or shared-debug)"
+	    echo >&2 "$platform cannot do shared (or shared-debug)"
 	fi
       fi
   esac
