more minor changes, output is more readable - warnings stick out more.
[git-p4: depot-paths = "//depot/qt/main/": change = 46935]

diff --git a/util/scripts/mkdists b/util/scripts/mkdists
--- a/util/scripts/mkdists
+++ b/util/scripts/mkdists
@@ -259,7 +259,8 @@ fi
 if [ "x$DO_DOC" = "xyes" ]; then
     QDOC_SRC="`dirname $QDOC_PATH`"
     if [ -d  "$QDOC_SRC" ]; then
-    	(cd "$QDOC_SRC"; qmake; make ) || die "Cannot build qdoc (${QDOC_SRC})"
+	status "Building qdoc.."
+    	(cd "$QDOC_SRC"; make qmake; make >/dev/null ) || die "Cannot build qdoc (${QDOC_SRC})"
     else
 	echo "Cannot find qdoc source, hopefully you have made sure it is up-to-date"
     fi
@@ -329,8 +330,8 @@ done
 status "Creating moc files.."
 pushd $DISTDIR/qt/src/moc >/dev/null 2>&1
 $QMAKE_PATH -spec $QTDIR/mkspecs/linux-g++ moc.pro -o Makefile >/dev/null 2>&1
-status `make moc_lex.cpp 2>&1`
-status `make moc_yacc.cpp 2>&1`
+status `make moc_lex.cpp >/dev/null`
+status `make moc_yacc.cpp >/dev/null`
 rm -f Makefile
 popd >/dev/null 2>&1
 
@@ -384,7 +385,7 @@ if [ -e  "$qgif" ]; then
 fi
 
 # changes files
-[ ! -f "$DISTDIR/qt/dist/changes-$REL_VERSION" ] && status "Warning: qt/dist/changes-$REL_VERSION does not exist"
+[ ! -f "$DISTDIR/qt/dist/changes-$REL_VERSION" ] && status "!! Warning: qt/dist/changes-$REL_VERSION does not exist !!"
 for a in `find $DISTDIR/qt/dist/ -name "changes-$REL_VERSION"`; do
     mv $a $DISTDIR/qt/`basename $a`
 done
@@ -406,7 +407,7 @@ if echo $REL_VERSION | grep $TYPE >/dev/null 2>&1; then
 else
     VERSION_STR=${REL_VERSION}${TYPE} && [ "$TYPE" = "-snapshot" ] && VERSION_STR=`date "+${VERSION_STR}-%Y%m%d"`
 fi
-[ "$DO_WIN" = "yes" ] && ! strings $DISTDIR/qt/dist/win/bin/moc.exe | grep "$VERSION_STR" >/dev/null 2>&1 && status "Warning: qt/dist/win/bin/moc.exe might not match"
+[ "$DO_WIN" = "yes" ] && ! strings $DISTDIR/qt/dist/win/bin/moc.exe | grep "$VERSION_STR" >/dev/null 2>&1 && status "!! Warning: qt/dist/win/bin/moc.exe might not match !!"
 sed -e "s,^\(\#define  *QT_VERSION  *\)[0-9]*$,\1${BRANCH_DIGITS},g" \
     -e "s,^\(\#define  *QT_VERSION_STR  *\)\".*\"$,\1\"${VERSION_STR}\",g" $qglobal >${TMP_FILE}
 mv ${TMP_FILE} $qglobal
@@ -824,8 +825,8 @@ for plat in mac win x11 embedded; do
 	#do the documentation
 	if [ "x$DO_DOC" = "xyes" ]; then
 	    status "Running qdoc.."
-	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc, stopped"
-	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/tools/linguist/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc (linguist), stopped"
+	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --warning-level=0 >/dev/null 2>&1 || die "could not run qdoc, stopped"
+	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/tools/linguist/qdoc.conf --warning-level=0 >/dev/null 2>&1 || die "could not run qdoc (linguist), stopped"
 	    find $PLATDIR/gif -exec mv {} $PLATDIR/doc/html/ \; >/dev/null 2>&1
 	    if [ "$plat" = "x11" ] || [ "$plat" = "embedded" ]; then
 		QTDIR=$PLATDIR/ $DISTDIR/qt/util/qdoc/man  $PLATDIR/ >/dev/null 2>&1 || die "could not run man, stopped"
