works in a crontab now
[git-p4: depot-paths = "//depot/qt/main/": change = 32925]

diff --git a/util/scripts/mkdists b/util/scripts/mkdists
--- a/util/scripts/mkdists
+++ b/util/scripts/mkdists
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+#customizing
+P4=/usr/local/bin/p4          #p4 location
+P4PORT=lupinella.troll.no:866 #point p4 to the correct server
+
 #internal variables
 CREATED_MANIFEST=no
 TMP_DIR=/tmp
@@ -216,41 +220,46 @@ if [ "$BRANCH" = "auto" ]; then
     fi
 fi
 
-BRANCH_DIGITS=`echo $BRANCH | sed "s,\.,,g" | sed "s,\(\d\d\d\).*,\1,"`
-[ -z "$BRANCH_DIGITS" ] && BRANCH_DIGITS="000"
-
 DISTDIR="${TMP_DIR}/qt-$BRANCH-$MYNAME-$$"
 
 #Checkout P4
 if [ -z $LOCAL_TREE ]; then
+    export P4PORT
     checkoutlabel=""
-    if ! p4 fstat //depot/qt/$BRANCH/doc.conf 2>&1 | grep " depotFile " >/dev/null 2>&1 ; then
+    if ! $P4 fstat //depot/qt/$BRANCH/doc.conf 2>&1 | grep " depotFile " >/dev/null 2>&1 ; then
 	die "//depot/qt/$BRANCH/... is not in the depot, stopped"
     fi
     if [ ! -z $LABEL ]; then
-	if ! p4 labels 2>&1 | grep "^Label $LABEL" >/dev/null 2>&1 ; then
+	if ! $P4 labels 2>&1 | grep "^Label $LABEL" >/dev/null 2>&1 ; then
 	    die "Label $LABEL does not exist, stopped"
 	fi
 
-	if p4 label -o $LABEL | grep '^Options:.*locked' >/dev/null 2>&1; then
+	if $P4 label -o $LABEL | grep '^Options:.*locked' >/dev/null 2>&1; then
 	    checkoutlabel="@${LABEL}"
 	fi
     fi
     status "Exporting the entire Qt depot $checkoutlabel..";
 
     tmpclient="qt-release-tmp-$MYNAME";
-    p4 client -t qt-release-3x -o $tmpclient >${TMP_FILE}
+    $P4 client -t qt-release-3x -o $tmpclient >${TMP_FILE}
     sed ${TMP_FILE} -e "s,^Root:.*,Root: $DISTDIR," -e "s,/qt/X.Y/,/qt/$BRANCH/,g" \
 	    -e "s,^\(Client: \).*,\1qt-release-tmp-$$," -e "s,\bnomodtime\b,modtime," | \
-      p4 -s client -i >/dev/null 2>&1
+      $P4 -s client -i >/dev/null 2>&1
 
-    p4 -s -c $tmpclient sync -f $DISTDIR/qt/...${checkoutlabel} >/dev/null 2>&1
+    $P4 -s -c $tmpclient sync -f $DISTDIR/qt/...${checkoutlabel} >/dev/null 2>&1
 else
     status "Copying Qt depot.."
     [ ! -d $DISTDIR/qt ] && mkdir -p $DISTDIR/qt
     cp -ar $LOCAL_TREE $DISTDIR/qt
 fi
 
+#setup branch correctly..
+if [ "$REL_VERSION" = "0.0.0" ]; then
+    REL_VERSION=`grep VERSION $DISTDIR/qt/src/qt.pro | awk '{print $3;}'`
+    BRANCH=$REL_VERSION
+fi
+BRANCH_DIGITS=`echo $BRANCH | sed "s,\.,,g" | sed "s,\(\d\d\d\).*,\1,"`
+[ -z "$BRANCH_DIGITS" ] && BRANCH_DIGITS="000"
 
 #get include files
 includefiles=`QTDIR=$DISTDIR/qt $DISTDIR/qt/bin/syncqt -show`
@@ -306,9 +315,9 @@ qglobal="$DISTDIR/qt/src/tools/qglobal.h"
 sed -e "s,\(\#define\s*QT_VERSION\s*\)[0-9]*,\1$BRANCH_DIGITS,g" \
     -e "s,\(\#define\s*QT_VERSION_STR\s+\"\)\([0-9.]*\),/1$BRANCH,g" $qglobal >${TMP_FILE}
 mv ${TMP_FILE} $qglobal
-type=`grep QT_VERSION_STR $DISTDIR/qt/src/tools/qglobal.h | awk '{ print $3 }' | sed 's,["0-9.]*\(-.*\)",\1,'`
-if [ "$type" != "-snapshot" ] && ! myexpr "$type" : "^-beta[0-9]*$"; then
-    die "The qt version is ${BRANCH}${type}, which confuses me terribly";
+TYPE=`grep QT_VERSION_STR $DISTDIR/qt/src/tools/qglobal.h | awk '{ print $3 }' | sed 's,["0-9.]*\(-.*\)",\1,'`
+if [ "$TYPE" != "-snapshot" ] && ! myexpr "$TYPE" : "^-beta[0-9]*$"; then
+    die "The qt version is ${BRANCH}${TYPE}, which confuses me terribly";
 fi
 
 #fix $Id
@@ -320,7 +329,7 @@ if [ "x$DO_ID" = "xyes" ]; then
 	    [ -x $a ] && execut=555
 
 	    mtime=`ls -l $a | awk '{ print $6,$7,$8 }'` #mtime is pretty bogus, but a quick hack..
-	    tag_ID="`echo $a | sed "s,^.*/,qt/,"`   ${REL_VERSION}${type}   edited $mtime"
+	    tag_ID="`echo $a | sed "s,^.*/,qt/,"`   ${REL_VERSION}${TYPE}   edited $mtime"
 	    sed "s,\(\$Id[:] \)[^\\$]*\\$,\1 ${tag_ID} \$,g" $a >${TMP_FILE}
 	    rm -f $a
 	    mv ${TMP_FILE} $a
@@ -347,6 +356,10 @@ public_file () {
 	 # no qdoc conf
 	 [ "$file_BASE" = "doc.conf" ] ||
 
+	 # internal docs
+	 [ "$file_BASE" = "TODO.txt" ] ||
+	 [ "$file_BASE" = "BUGS.txt" ] ||
+	 
 	 # no make.help
 	 [ "$file_BASE" = "make.help" ] ||
 
@@ -384,7 +397,7 @@ public_file () {
 	 myexpr "$file" : '^dist\/' ||
 
 	 # no tests
-	 myexpr "$file" : '^tests\/.*'
+	 myexpr "$file" : '\(.*\/\)*tests\/.*'
      then
 	    KEEP=no
      elif
@@ -517,9 +530,9 @@ copy_platform_files() {
 	[ ! -d $final_dir ] && mkdir -p $final_dir
 	[ -f $o_dir/$o_file ] && rm -f $o_dir/$o_file
 	if [ -f $dir/$a_file ] && [ ! -e $o_dir/$o_file ]; then
-	    sed -e "s/%YEAR%/$year/g" -e "s/%VERSION%/${BRANCH}${type}/g" \
+	    sed -e "s/%YEAR%/$year/g" -e "s/%VERSION%/${BRANCH}${TYPE}/g" \
 		-e "s/$VERSIONWIN%/${BRANCH_DIGITS}/g" $dir/$a_file >${TMP_FILE}
-	    if [ "$type" = "-snapshot" ]; then
+	    if [ "$TYPE" = "-snapshot" ]; then
 		sed -e "s/%SNAPSHOTONLY\([^%]*\)%/\1/g" -e "s/%STABLEONLY[^%]*%//g" ${TMP_FILE} >$o_dir/$o_file
 	    else
 		sed -e "s/%SNAPSHOTONLY[^%]*%//g" -e "s/%STABLEONLY\([^%]\)*%/\1/g" ${TMP_FILE} >$o_dir/$o_file
@@ -589,7 +602,7 @@ for plat in mac win x11 qws; do
 	status "*** Packing $edition... *****" "1"
 	if [ "$REL_VERSION" = "0.0.0" ]; then
 	    PLATNAME=`date "+qt-${plat}-${edition}-%d-%m-%y${type}"`
-	else
+        else
 	    PLATNAME=qt-${plat}-${edition}-${REL_VERSION}${type}
 	fi
 	PLATDIR=$DISTDIR/$PLATNAME
@@ -691,7 +704,7 @@ for plat in mac win x11 qws; do
 	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc, stopped"
 	    find $PLATDIR/gif -exec mv {} $PLATDIR/doc/html/ \; >/dev/null 2>&1
 	    if [ "$plat" = "x11" ] || [ "$plat" = "qws" ]; then
-		$DISTDIR/qt/util/qdoc/man  $PLATDIR/ >/dev/null 2>&1 || die "could not run man, stopped"
+		QTDIR=$PLATDIR/ $DISTDIR/qt/util/qdoc/man  $PLATDIR/ >/dev/null 2>&1 || die "could not run man, stopped"
 	    fi
 	fi
 	if [ "$plat" = "win" ]; then
