p4i integration Integrate 111202 from 3 to main: Integrate 111201 from 3.2 to 3: use += when adding DEFINEs for qdoc, otherwise we'll remove all the previous ones.
[git-p4: depot-paths = "//depot/qt/main/": change = 111203]

diff --git a/util/scripts/mkdists b/util/scripts/mkdists
--- a/util/scripts/mkdists
+++ b/util/scripts/mkdists
@@ -1032,7 +1032,7 @@ for plat in mac win x11 qnx6 embedded; do
             done
 	    status "Running qdoc.."
 	    if [ "$edition" != "free" ]; then
-		QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --define=commercial --warning-level=0 >>$LOG 2>&1 || die "could not run qdoc, stopped"
+		QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --define+=commercial --warning-level=0 >>$LOG 2>&1 || die "could not run qdoc, stopped"
 	    else
 		QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --warning-level=0 >>$LOG 2>&1 || die "could not run qdoc, stopped"
 	    fi
