p4i integration Integrate 110027 from 3 to main: Integrate 110025 from 3.2 to 3: change qdoc to run with --define==commercial for all editions except free. This will among other things make the index.html for doc/html say Qt Reference Documentation (Commercial Edition)
[git-p4: depot-paths = "//depot/qt/main/": change = 110028]

diff --git a/util/scripts/mkdists b/util/scripts/mkdists
--- a/util/scripts/mkdists
+++ b/util/scripts/mkdists
@@ -1026,7 +1026,11 @@ for plat in mac win x11 qnx6 embedded; do
 		fi
             done
 	    status "Running qdoc.."
-	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --warning-level=0 >>$LOG 2>&1 || die "could not run qdoc, stopped"
+	    if [ "$edition" != "free" ]; then
+		QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --define=commercial --warning-level=0 >>$LOG 2>&1 || die "could not run qdoc, stopped"
+	    else
+		QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf --warning-level=0 >>$LOG 2>&1 || die "could not run qdoc, stopped"
+	    fi
 	    find $PLATDIR/gif -exec mv {} $PLATDIR/doc/html/ \; >>$LOG 2>&1
 	    if [ "$plat" = "x11" ] || [ "$plat" = "embedded" ] || [ "$plat" = "qnx6" ]; then
 		QTDIR=$PLATDIR/ $DISTDIR/qt/util/qdoc/man  $PLATDIR/ >>$LOG 2>&1 || die "could not run man, stopped"
