Add some docs about editions (free, prof, ent) Also mark which modules belong to enterprise only.
[git-p4: depot-paths = "//depot/qt/main/": change = 39425]

diff --git a/util/scripts/mkdists b/util/scripts/mkdists
--- a/util/scripts/mkdists
+++ b/util/scripts/mkdists
@@ -76,7 +76,7 @@ showhelp()
     echo
 
     echo "Paths:"
-    echo "  -manifest <file>     : Specify path to manifest file (will create)"
+    echo "  -manifest <file>     : Specify path and filename of manifest file (will create)"
     echo "  -outdir <directory>  : Where to put all things (default $OUT_TREE)"
     echo "  -qdoc <executable>   : Where qdoc lives (default $QDOC_PATH)"
     echo
@@ -752,8 +752,10 @@ for plat in mac win x11 embedded; do
 	#do the documentation
 	if [ "x$DO_DOC" = "xyes" ]; then
 	    status "Running qdoc.."
+	    echo $PLATDIR
+	    echo "$QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf"
 	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/util/qdoc/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc, stopped"
-	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/tools/linguist/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc, stopped"
+	    QTDIR=$PLATDIR $QDOC_PATH $DISTDIR/qt/tools/linguist/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc (linguist), stopped"
 	    find $PLATDIR/gif -exec mv {} $PLATDIR/doc/html/ \; >/dev/null 2>&1
 	    if [ "$plat" = "x11" ] || [ "$plat" = "embedded" ]; then
 		QTDIR=$PLATDIR/ $DISTDIR/qt/util/qdoc/man  $PLATDIR/ >/dev/null 2>&1 || die "could not run man, stopped"
