p4i integration Integrate change 79845 from 3.1 to main. Description for change 79845:
: Change 79845 by porten@porten-komet on 2002/11/13 13:54:00
: 
: 	properly qmake the qdoc Makefile
: 	check for qmake a bit earlier because of above change
: 
: Affected files ...
: 
: ... //depot/qt/3.1/util/scripts/mkdists#3 edit

[git-p4: depot-paths = "//depot/qt/main/": change = 79846]

diff --git a/util/scripts/mkdists b/util/scripts/mkdists
--- a/util/scripts/mkdists
+++ b/util/scripts/mkdists
@@ -279,17 +279,17 @@ if [ "$BRANCH" = "auto" ]; then
 fi
 
 #make sure everything is in order before bothering..
+[ ! -x "$QMAKE_PATH" ] && die "qmake not found, failed (${QMAKE_PATH})"
 if [ "x$DO_DOC" = "xyes" ]; then
     QDOC_SRC="`dirname $QDOC_PATH`"
     if [ -d  "$QDOC_SRC" ]; then
 	status "Building qdoc.."
-    	(cd "$QDOC_SRC"; make qmake; make >/dev/null ) || die "Cannot build qdoc (${QDOC_SRC})"
+    	(cd "$QDOC_SRC"; "$QMAKE_PATH" qdoc.pro; make >/dev/null ) || die "Cannot build qdoc (${QDOC_SRC})"
     else
 	echo "Cannot find qdoc source, hopefully you have made sure it is up-to-date"
     fi
     [ ! -x "$QDOC_PATH" ] && die "qdoc not found, failed (${QDOC_PATH})"
 fi
-[ ! -x "$QMAKE_PATH" ] && die "qmake not found, failed (${QMAKE_PATH})"
 
 if [ "x$DO_PKG" = "xyes" ]; then
     QPKG_SRC="`dirname $QPKG_PATH`"
